version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: core-js
    versions:
    - 3.10.2
    - 3.11.0
  - dependency-name: "@vue/test-utils"
    versions:
    - 2.0.0-rc.5
  - dependency-name: vue-demi
    versions:
    - 0.7.3
    - 0.7.4
    - 0.7.5
  - dependency-name: eslint
    versions:
    - 7.23.0
